// ============================================================
// shared/src/types.ts — FROZEN CONTRACT (see design-contract.md)
// ============================================================

// ---------- Core board ----------

/** Black always moves first. */
export type Player = 'B' | 'W';
export type Cell = Player | null;

/**
 * 64 cells, row-major. index = row * 8 + col.
 * row 0 = rank "1" (top of the screen), col 0 = file "a" (left).
 * Start position: d4=27 'W', e4=28 'B', d5=35 'B', e5=36 'W'.
 */
export type Board = Cell[];

/** Integer 0..63. Algebraic: squareToAlg(19) === 'd3'. */
export type Square = number;

export interface Move {
  player: Player;
  /** null = pass. Passes are generated by the server only; clients never send them. */
  square: Square | null;
}

export interface PlayedMove extends Move {
  /** 1-based, contiguous, passes included. */
  ply: number;
  /** Squares flipped by this move ([] for a pass). Does not include `square` itself. */
  flipped: Square[];
}

// ---------- Game ----------

export type GameStatus = 'waiting' | 'active' | 'finished';
export type Winner = Player | 'draw';
/** 'forfeit': a tournament organizer ended the game against a player who didn't show. */
export type EndReason = 'normal' | 'resign' | 'forfeit';
export type AnalysisStatus = 'none' | 'pending' | 'running' | 'done' | 'failed';

export interface PlayerInfo {
  /** Display name: the account's username for signed-in players, free text for guests. */
  name: string;
  /** The seat's account, or null for a guest seat. */
  accountId: string | null;
}

/** Lightweight game header: used in lists, in GameState, and in AnalysisResult. */
export interface GameSummary {
  gameId: string;
  status: GameStatus;
  players: { B: PlayerInfo; W: PlayerInfo | null }; // W is null while status === 'waiting'
  counts: { B: number; W: number };
  winner: Winner | null;        // non-null iff status === 'finished'
  endReason: EndReason | null;  // non-null iff status === 'finished'
  analysisStatus: AnalysisStatus;
  createdAt: string;            // ISO 8601
  finishedAt: string | null;    // ISO 8601
}

/** Full live state. The server always sends the whole thing, never diffs. */
export interface GameState extends GameSummary {
  board: Board;
  /** Whose turn it is. null unless status === 'active'. */
  turn: Player | null;
  /** Legal squares for `turn`. [] when turn is null. Clients use this for hints; never compute rules client-side. */
  legalMoves: Square[];
  /** Full history, including server-generated passes. */
  moves: PlayedMove[];
  /**
   * === moves.length. Clients must ignore any GameState whose version is
   * strictly LOWER than the one they hold (equal is fine: resign / analysis
   * status changes re-broadcast at the same version).
   */
  version: number;
}

// ---------- Analysis ----------

/**
 * All evals are in "disc" units from BLACK's point of view (+ = Black better),
 * like chess engines report from White's POV. Heuristic evals are scaled to
 * roughly approximate final disc differential. When `exact` is true the value
 * IS the final disc differential under perfect play. Range is always [-64, 64].
 */
export type MoveClass = 'best' | 'good' | 'inaccuracy' | 'mistake' | 'blunder' | 'forced';

/** Rule-based coaching tags. May be [] (backend fills these if time allows). */
export type Motif =
  | 'took_corner'     // played a corner
  | 'missed_corner'   // a corner was legal and the best move, but not played
  | 'allowed_corner'  // after this move the opponent has a legal corner they didn't have before
  | 'x_square'        // played b2/g2/b7/g7 while the adjacent corner is empty
  | 'c_square';       // played a C-square (a1-adjacent edge squares etc.) while the adjacent corner is empty

export interface CandidateMove {
  square: Square;
  eval: number; // Black POV
}

export interface PlyAnalysis {
  ply: number;
  player: Player;
  square: Square | null;        // null = pass
  flipped: Square[];
  boardBefore: Board;
  boardAfter: Board;
  /** Black-POV eval of the position before this ply, assuming best play (= best candidate's eval). */
  evalBefore: number;
  /** Black-POV eval after the move actually played. Plot this for the eval graph. */
  evalAfter: number;
  /** Discs given up versus the best move, from the MOVER's POV. Always >= 0. 0 for forced moves. */
  loss: number;
  /** Engine's best move. null only for passes. */
  bestSquare: Square | null;
  classification: MoveClass;
  isBlunder: boolean;           // === (classification === 'blunder')
  /** Up to 3 root moves, best-first from the mover's POV. Evals are Black POV. */
  candidates: CandidateMove[];
  motifs: Motif[];
  depth: number;                // search depth reached
  exact: boolean;               // true if solved to the end of the game
}

export interface PlayerAnalysisSummary {
  /** 0..100. 100 * mean(exp(-loss / 6)) over this player's non-forced moves; 100 if none. */
  accuracy: number;
  /** Mean loss over non-forced moves; 0 if none. */
  avgLoss: number;
  counts: Record<MoveClass, number>;
}

export interface AnalysisResult {
  game: GameSummary;
  status: AnalysisStatus;
  /** Non-null only while status === 'running'. */
  progress: { done: number; total: number } | null;
  /** Populated (length === moves.length) iff status === 'done'; otherwise []. */
  plies: PlyAnalysis[];
  /** Non-null iff status === 'done'. */
  summary: { B: PlayerAnalysisSummary; W: PlayerAnalysisSummary } | null;
}

// ---------- REST DTOs ----------

export type ErrorCode =
  | 'BAD_REQUEST'
  | 'GAME_NOT_FOUND'
  | 'GAME_FULL'
  | 'GAME_NOT_ACTIVE'
  | 'NOT_YOUR_TURN'
  | 'ILLEGAL_MOVE'
  | 'BAD_TOKEN'
  | 'UNAUTHORIZED'     // missing/invalid/expired access token on an account endpoint
  | 'USERNAME_TAKEN'
  | 'FORBIDDEN'            // signed in, but not allowed (e.g. not the tournament's organizer)
  | 'TOURNAMENT_NOT_FOUND'
  | 'TOURNAMENT_FULL'
  | 'TOURNAMENT_NOT_OPEN'  // the action doesn't fit the tournament's current status
  | 'INTERNAL';

/** Body of every non-2xx REST response. */
export interface ApiError {
  error: { code: ErrorCode; message: string };
}

export interface CreateGameRequest { name: string }   // trimmed, 1..24 chars
export interface JoinGameRequest { name: string }     // trimmed, 1..24 chars

/** Returned by both create (color 'B') and join (color 'W'). */
export interface SeatResponse {
  gameId: string;
  color: Player;
  playerToken: string;
}

export interface ListGamesResponse {
  games: GameSummary[];
}

// ---------- Accounts ----------
// Optional. Identity comes from Supabase Auth (a bearer access token on REST calls);
// the account row itself lives in our Postgres. Guests never touch these endpoints.

export interface Account {
  /** Supabase auth user id (the JWT `sub`). */
  id: string;
  /** 3..20 chars of [A-Za-z0-9_], unique case-insensitively. Used as the seat name in games. */
  username: string;
  createdAt: string;            // ISO 8601
}

/** GET /api/me. `account` is null when signed in but no username has been claimed yet. */
export interface MeResponse {
  account: Account | null;
}

/** PUT /api/me: claim (or change) the username. */
export interface ClaimUsernameRequest { username: string }

// ---------- Tournaments ----------
// Single elimination, 2..8 players, accounts only. Reads are public; every write needs an
// account with a claimed username. Bracket math lives in bracket.ts.

export type TournamentStatus = 'registering' | 'active' | 'finished';

export interface TournamentPlayer {
  accountId: string;
  username: string;
}

export interface TournamentSummary {
  tournamentId: string;
  name: string;                 // trimmed, 1..40 chars
  status: TournamentStatus;
  /** Runs the tournament (starts it, forfeits no-shows). Not a player unless they also entered. */
  organizer: TournamentPlayer;
  maxPlayers: number;           // 2..8
  entrantCount: number;
  winner: TournamentPlayer | null;  // non-null iff status === 'finished'
  createdAt: string;            // ISO 8601
  startedAt: string | null;
  finishedAt: string | null;
}

export interface TournamentEntrant extends TournamentPlayer {
  /** 1 = top seed. Assigned (randomly) on start; null while registering. */
  seed: number | null;
}

/**
 * 'pending': waiting on a player from an earlier match. 'playing': game created.
 * 'decided': has a winner (a round-1 match against an empty slot is a bye, decided with no game).
 */
export type MatchStatus = 'pending' | 'playing' | 'decided';

export interface TournamentMatch {
  round: number;                // 1-based; round === rounds is the final
  slot: number;                 // 0-based within the round, top to bottom
  status: MatchStatus;
  /** The upper slot's player takes Black. A drawn game goes to White. */
  black: TournamentPlayer | null;
  white: TournamentPlayer | null;
  gameId: string | null;
  winner: TournamentPlayer | null;
}

export interface TournamentDetail extends TournamentSummary {
  entrants: TournamentEntrant[]; // join order while registering, seed order once started
  /** log2(bracket size); 0 while registering. */
  rounds: number;
  /** Every match of every round (empty while registering), ordered by round then slot. */
  matches: TournamentMatch[];
}

export interface ListTournamentsResponse {
  tournaments: TournamentSummary[];
}

/** POST /api/tournaments */
export interface CreateTournamentRequest {
  name: string;
  maxPlayers?: number;          // default 8
}

/** POST /api/tournaments/:id/matches/:round/:slot/forfeit (organizer only) */
export interface ForfeitRequest {
  loser: Player;
}

// ---------- Socket.IO ----------

export type Ack<T extends object = {}> =
  | ({ ok: true } & T)
  | { ok: false; error: ErrorCode; message: string };

export interface SubscribePayload {
  gameId: string;
  /** Omit to watch as a spectator. */
  playerToken?: string;
}
export interface SubscribeResult {
  state: GameState;
  /** Seat that the token maps to; null for spectators or an invalid/missing token. */
  you: Player | null;
}

export interface MovePayload {
  gameId: string;
  playerToken: string;
  square: Square;
}

export interface ResignPayload {
  gameId: string;
  playerToken: string;
}

export interface AnalysisProgressPayload {
  gameId: string;
  done: number;
  total: number;
}

export interface AnalysisReadyPayload {
  gameId: string;
  status: 'done' | 'failed';
}

/** Pass as generics: io<ClientToServerEvents, ServerToClientEvents>(), new Server<ClientToServerEvents, ServerToClientEvents>() */
export interface ClientToServerEvents {
  'game:subscribe': (p: SubscribePayload, ack: (r: Ack<SubscribeResult>) => void) => void;
  'game:move': (p: MovePayload, ack: (r: Ack) => void) => void;
  'game:resign': (p: ResignPayload, ack: (r: Ack) => void) => void;
}

export interface ServerToClientEvents {
  'game:state': (s: GameState) => void;
  'analysis:progress': (p: AnalysisProgressPayload) => void;
  'analysis:ready': (p: AnalysisReadyPayload) => void;
}
